#!/bin/sh
have=ATM_LINUX . auto/have_headers

atm_spacer='
'

cc_aux_flags="$CC_AUX_FLAGS"
CC_AUX_FLAGS="$cc_aux_flags -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64"


# Linux kernel version

version=$((`uname -r \
    | sed -n -e 's/^\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/ \
                                                 \1*256*256+\2*256+\3/p' \
             -e 's/^\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1*256*256+\2*256/p'`))

version=${version:-0}


# posix_fadvise64() had been implemented in 2.5.60

if [ $version -lt 132412 ]; then
    have=ATM_HAVE_POSIX_FADVISE . auto/nohave
fi

# epoll, EPOLLET version

atm_feature="epoll"
atm_feature_name="ATM_HAVE_EPOLL"
atm_feature_run=yes
atm_feature_incs="#include <sys/epoll.h>"
atm_feature_path=
atm_feature_libs=
atm_feature_test="int efd = 0;
                  struct epoll_event ee;
                  ee.events = EPOLLIN|EPOLLOUT|EPOLLET;
                  ee.data.ptr = NULL;
                  (void) ee;
                  efd = epoll_create(100);
                  if (efd == -1) return 1;"
. auto/feature

if [ $atm_found = yes ]; then
    have=ATM_HAVE_CLEAR_EVENT . auto/have
    CORE_SRCS="$CORE_SRCS $EPOLL_SRCS"
    EVENT_MODULES="$EVENT_MODULES $EPOLL_MODULE"
    EVENT_FOUND=YES


    # EPOLLRDHUP appeared in Linux 2.6.17, glibc 2.8

    atm_feature="EPOLLRDHUP"
    atm_feature_name="ATM_HAVE_EPOLLRDHUP"
    atm_feature_run=no
    atm_feature_incs="#include <sys/epoll.h>"
    atm_feature_path=
    atm_feature_libs=
    atm_feature_test="int efd = 0, fd = 0;
                      struct epoll_event ee;
                      ee.events = EPOLLIN|EPOLLRDHUP|EPOLLET;
                      ee.data.ptr = NULL;
                      epoll_ctl(efd, EPOLL_CTL_ADD, fd, &ee)"
    . auto/feature


    # EPOLLEXCLUSIVE appeared in Linux 4.5, glibc 2.24

    atm_feature="EPOLLEXCLUSIVE"
    atm_feature_name="ATM_HAVE_EPOLLEXCLUSIVE"
    atm_feature_run=no
    atm_feature_incs="#include <sys/epoll.h>"
    atm_feature_path=
    atm_feature_libs=
    atm_feature_test="int efd = 0, fd = 0;
                      struct epoll_event ee;
                      ee.events = EPOLLIN|EPOLLEXCLUSIVE;
                      ee.data.ptr = NULL;
                      epoll_ctl(efd, EPOLL_CTL_ADD, fd, &ee)"
    . auto/feature
fi


# O_PATH and AT_EMPTY_PATH were introduced in 2.6.39, glibc 2.14

atm_feature="O_PATH"
atm_feature_name="ATM_HAVE_O_PATH"
atm_feature_run=no
atm_feature_incs="#include <sys/types.h>
                  #include <sys/stat.h>
                  #include <fcntl.h>"
atm_feature_path=
atm_feature_libs=
atm_feature_test="int fd; struct stat sb;
                  fd = openat(AT_FDCWD, \".\", O_PATH|O_DIRECTORY|O_NOFOLLOW);
                  if (fstatat(fd, \"\", &sb, AT_EMPTY_PATH) != 0) return 1"
. auto/feature


# sendfile()

CC_AUX_FLAGS="$cc_aux_flags -D_GNU_SOURCE"
atm_feature="sendfile()"
atm_feature_name="ATM_HAVE_SENDFILE"
atm_feature_run=yes
atm_feature_incs="#include <sys/sendfile.h>
                  #include <errno.h>"
atm_feature_path=
atm_feature_libs=
atm_feature_test="int s = 0, fd = 1;
                  ssize_t n; off_t off = 0;
                  n = sendfile(s, fd, &off, 1);
                  if (n == -1 && errno == ENOSYS) return 1"
. auto/feature

if [ $atm_found = yes ]; then
    CORE_SRCS="$CORE_SRCS $LINUX_SENDFILE_SRCS"
fi


# sendfile64()

CC_AUX_FLAGS="$cc_aux_flags -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64"
atm_feature="sendfile64()"
atm_feature_name="ATM_HAVE_SENDFILE64"
atm_feature_run=yes
atm_feature_incs="#include <sys/sendfile.h>
                  #include <errno.h>"
atm_feature_path=
atm_feature_libs=
atm_feature_test="int s = 0, fd = 1;
                  ssize_t n; off_t off = 0;
                  n = sendfile(s, fd, &off, 1);
                  if (n == -1 && errno == ENOSYS) return 1"
. auto/feature


atm_include="sys/prctl.h"; . auto/include

# prctl(PR_SET_DUMPABLE)

atm_feature="prctl(PR_SET_DUMPABLE)"
atm_feature_name="ATM_HAVE_PR_SET_DUMPABLE"
atm_feature_run=yes
atm_feature_incs="#include <sys/prctl.h>"
atm_feature_path=
atm_feature_libs=
atm_feature_test="if (prctl(PR_SET_DUMPABLE, 1, 0, 0, 0) == -1) return 1"
. auto/feature


# sched_setaffinity()

atm_feature="sched_setaffinity()"
atm_feature_name="ATM_HAVE_SCHED_SETAFFINITY"
atm_feature_run=no
atm_feature_incs="#include <sched.h>"
atm_feature_path=
atm_feature_libs=
atm_feature_test="cpu_set_t mask;
                  CPU_ZERO(&mask);
                  sched_setaffinity(0, sizeof(cpu_set_t), &mask)"
. auto/feature


# crypt_r()

atm_feature="crypt_r()"
atm_feature_name="ATM_HAVE_GNU_CRYPT_R"
atm_feature_run=no
atm_feature_incs="#include <crypt.h>"
atm_feature_path=
atm_feature_libs=-lcrypt
atm_feature_test="struct crypt_data  cd;
                  crypt_r(\"key\", \"salt\", &cd);"
. auto/feature


atm_include="sys/vfs.h";     . auto/include


CC_AUX_FLAGS="$cc_aux_flags -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64"
