#!/bin/sh
atm_feature="C compiler"
atm_feature_name=
atm_feature_run=yes
atm_feature_incs=
atm_feature_path=
atm_feature_libs=
atm_feature_test=
. auto/feature


if [ $atm_found = no ]; then
    echo
    echo $0: error: C compiler $CC is not found
    echo
    exit 1
fi


if `$CC -v 2>&1 | grep 'gcc version' >/dev/null 2>&1`; then
    ATM_CC_NAME=gcc
    echo " + using GNU C compiler"
elif `$CC -v 2>&1 | grep '\(clang\|LLVM\) version' >/dev/null 2>&1`; then
    ATM_CC_NAME=clang
    echo " + using Clang C compiler"
else
    ATM_CC_NAME=unknown
fi
