#!/bin/sh
atm_include="unistd.h";      . auto/include
atm_include="inttypes.h";    . auto/include
atm_include="limits.h";      . auto/include
atm_include="sys/filio.h";   . auto/include
atm_include="sys/param.h";   . auto/include
atm_include="sys/mount.h";   . auto/include
atm_include="sys/statvfs.h"; . auto/include
atm_include="crypt.h";       . auto/include
