#!/bin/sh
test -d $ATM_BUILD || mkdir -p $ATM_BUILD
echo > $ATM_AUTO_SYS_HEADERS_H
echo > $ATM_AUTOCONF_ERR
echo > $ATM_AUTO_CONFIG_H

if [ $ATM_DEBUG = YES ]; then
    have=ATM_DEBUG . auto/have
fi

if [ ".$ATM_BINARY_NAME" = "." ]; then
    echo "ATM_BINARY_NAME can not be empty"
    exit 1
else
    have=ATM_BINARY_NAME 
    value="\"$ATM_BINARY_NAME\""
    . auto/define
fi

# platform info
echo "checking for OS"
echo " + $ATM_SYSTEM $ATM_RELEASE $ATM_MACHINE"

# create Makefile on Top Level
cat << END > Makefile
default:	build
clean:
	rm -rf Makefile $ATM_BUILD
rmobj:
	rm build/$ATM_BINARY_NAME
	find build/src -type f -name '*.o' -delete
.PHONY:build
build:
	\$(MAKE) -f $ATM_MAKEFILE
install:
	\$(MAKE) -f $ATM_MAKEFILE install
END

if [ -z "$ATM_GROUP" ]; then
    if [ $ATM_USER = nobody ]; then
        if grep nobody /etc/group 2>&1 >/dev/null; then
            echo "checking for nobody group ... found"
            ATM_GROUP=nobody
        else
            echo "checking for nobody group ... not found"

            if grep nogroup /etc/group 2>&1 >/dev/null; then
                echo "checking for nogroup group ... found"
                ATM_GROUP=nogroup
            else
                echo "checking for nogroup group ... not found"
                ATM_GROUP=nobody
            fi
        fi
    else
        ATM_GROUP=$ATM_USER
    fi
fi

#------------------------------------------------------------------

if [ $ATM_UNIT_TEST = YES ]; then
    have=ATM_UNIT_TEST . auto/have
    have=ATM_UNIT_TEST_SKIP value=$ATM_UNIT_TEST_SKIP . auto/define
    have=ATM_UNIT_TEST_PREP value=$ATM_UNIT_TEST_PREP . auto/define
    have=ATM_UNIT_TEST_ONLY value=$ATM_UNIT_TEST_ONLY . auto/define
    have=ATM_UNIT_TEST_LV value=$ATM_UNIT_TEST_LV . auto/define
fi

have=ATM_USER value="\"$ATM_USER\"" . auto/define
have=ATM_GROUP value="\"$ATM_GROUP\"" . auto/define
have=ATM_BUILD value="\"$ATM_BUILD\"" . auto/define
have=ATM_PREFIX value="\"$ATM_PREFIX/\"" . auto/define
have=ATM_CONF_PREFIX value="\"$ATM_CONF_PREFIX/\"" . auto/define
have=ATM_SBIN_PATH value="\"$ATM_SBIN_PATH\"" . auto/define
have=ATM_CONF_PATH value="\"$ATM_CONF_PATH\"" . auto/define
have=ATM_PID_PATH value="\"$ATM_PID_PATH\"" . auto/define
have=ATM_LOCK_PATH value="\"$ATM_LOCK_PATH\"" . auto/define
have=ATM_ERROR_LOG_PATH value="\"$ATM_ERROR_LOG_PATH\"" . auto/define
