#!/bin/sh
#convert relative path to absolute path for installation
ATM_CONF_PREFIX=`dirname $ATM_PREFIX/$ATM_CONF_PATH`
cat << END                                                    >> $ATM_MAKEFILE
install:	build $ATM_INSTALL_PERL_MODULES
	test -d '$ATM_PREFIX' || mkdir -p '$ATM_PREFIX'
	test -d '`dirname "$ATM_PREFIX/$ATM_SBIN_PATH"`' || mkdir -p '`dirname "$ATM_PREFIX/$ATM_SBIN_PATH"`'
	test ! -f '$ATM_PREFIX/$ATM_SBIN_PATH' || mv '$ATM_PREFIX/$ATM_SBIN_PATH' '$ATM_PREFIX/$ATM_SBIN_PATH.old'
	cp $ATM_BUILD/$ATM_BINARY_NAME '$ATM_PREFIX/$ATM_SBIN_PATH'
	test -d '$ATM_CONF_PREFIX' || mkdir -p '$ATM_CONF_PREFIX'
	test -f '$ATM_PREFIX/$ATM_CONF_PATH' || cp config/$ATM_BINARY_NAME.conf '$ATM_PREFIX/$ATM_CONF_PATH'
	cp conf/$ATM_BINARY_NAME.conf '$ATM_CONF_PREFIX/$ATM_BINARY_NAME.conf.default'
	test -d '`dirname "$ATM_PREFIX/$ATM_PID_PATH"`' || mkdir -p '`dirname "$ATM_PREFIX/$ATM_PID_PATH"`'
END

if test -n "$ATM_ERROR_LOG_PATH"; then
    cat << END                                                >> $ATM_MAKEFILE
	test -d '`dirname "$ATM_PREFIX/$ATM_ERROR_LOG_PATH"`' || mkdir -p '`dirname "$ATM_PREFIX/$ATM_ERROR_LOG_PATH"`'
END

fi
