#!/bin/sh
echo "creating $ATM_MAKEFILE"

mkdir -p $ATM_BUILD/src/core \
         $ATM_BUILD/src/os/unix \
         $ATM_BUILD/src/test \
         $ATM_BUILD/src/test/core \
         $ATM_BUILD/src/test/os \
         $ATM_BUILD/src/test/os/unix


cat << END > $ATM_MAKEFILE
CC = $CC
CFLAGS = $CFLAGS
LINK = $LINK

END

atm_all_srcs="$CORE_SRCS"

# the core dependencies and include paths

atm_deps=`echo $CORE_DEPS $ATM_AUTO_CONFIG_H $ATM_AUTO_SYS_HEADERS_H \
    | sed -e "s/  *\([^ ][^ ]*\)/$atm_regex_cont\1/g"`

atm_incs=`echo $CORE_INCS $ATM_BUILD \
    | sed -e "s/  *\([^ ][^ ]*\)/$atm_regex_cont$atm_include_opt\1/g"`

cat << END >> $ATM_MAKEFILE
CORE_DEPS = $atm_deps

CORE_INCS = $atm_include_opt$atm_incs

END

# atmcache
atm_all_objs=`echo $atm_all_srcs \
    | sed -e "s#\([^ ]*\.\)c#$ATM_BUILD\/\1$atm_objext#g"`
atm_deps=`echo $atm_all_objs $LINK_DEPS \
    | sed -e "s/  *\([^ ][^ ]*\)/$atm_regex_cont\1/g"`
atm_build=`echo $atm_all_objs \
    | sed -e "s/  *\([^ ][^ ]*\)/$atm_regex_cont\1/g"`

atm_libs=
if test -n "$ATM_LD_OPT$CORE_LIBS"; then
    atm_libs=`echo $ATM_LD_OPT $CORE_LIBS | sed -e "s/^/$atm_regex_cont/"`
fi

atm_link=${CORE_LINK:+`echo $CORE_LINK \
    | sed -e "s/^/$atm_regex_cont/"`}

atm_main_link=${MAIN_LINK:+`echo $MAIN_LINK \
    | sed -e "s/^/$atm_regex_cont/"`}

cat << END >> $ATM_MAKEFILE
build:	binary 

binary:	${ATM_BUILD}/atmcache

${ATM_BUILD}/atmcache:	$atm_deps

	\$(LINK) -o ${ATM_BUILD}/atmcache \\
	$atm_build$atm_libs$atm_link$atm_main_link

END


# the core sources
atm_cc="\$(CC) $atm_compile_opt \$(CFLAGS) \$(CORE_INCS)"
for atm_src in $atm_all_srcs
do
    atm_obj=`echo $atm_src \
        | sed -e "s#^\(.*\.\)c\\$#${ATM_BUILD}\/\1$atm_objext#g"`

    cat << END >> $ATM_MAKEFILE
$atm_obj:	\$(CORE_DEPS)$atm_cont$atm_src
	$atm_cc$atm_tab$atm_objout$atm_obj$atm_tab$atm_src

END
done
