#!/bin/sh
ATM_DEBUG=YES
#LV:
#0: Do not process unit test. gen pure binary
#1: Do unit test. before service started
#2: Do unit test only and DO NOT start service
ATM_UNIT_TEST=YES
ATM_UNIT_TEST_SKIP=0
ATM_UNIT_TEST_PREP=1
ATM_UNIT_TEST_ONLY=2
ATM_UNIT_TEST_LV=$ATM_UNIT_TEST_SKIP

############ PLATFORM #############
ATM_SYSTEM=`uname -s 2>/dev/null`
ATM_RELEASE=`uname -r 2>/dev/null`
ATM_MACHINE=`uname -m 2>/dev/null`
ATM_PLATFORM="$ATM_SYSTEM:$ATM_RELEASE:$ATM_MACHINE";

############ GLOBAL #############
ATM_BUILD=build
ATM_PREFIX=${ATM_PREFIX:-/usr/local/atmcache}

ATM_USER=${ATM_USER:-nobody}
ATM_GROUP=

USE_THREADS=NO
ATM_FILE_AIO=NO
EVENT_FOUND=NO
EVENT_POLL=NO
ATM_CPU_CACHE_LINE=

############ LIB CONFIGURE #############
ATM_LIBATOMIC=YES

############ CONFIGURE  #############
ATM_MAKEFILE=$ATM_BUILD/Makefile
ATM_AUTOTEST=$ATM_BUILD/autotest
ATM_AUTOCONF_ERR=$ATM_BUILD/autoconf.err
ATM_AUTO_SYS_HEADERS_H=$ATM_BUILD/atm_auto_headers.h
ATM_AUTO_CONFIG_H=$ATM_BUILD/atm_auto_config.h

############ INSTALL #############
ATM_SBIN_PATH=${ATM_SBIN_PATH:-sbin/atmcache}
ATM_CONF_PATH=${ATM_CONF_PATH:-config/atmcache.conf}
ATM_CONF_PREFIX=`dirname $ATM_CONF_PATH`
ATM_PID_PATH=${ATM_PID_PATH:-logs/atmcache.pid}
ATM_LOCK_PATH=${ATM_LOCK_PATH:-logs/atmcache.lock}
ATM_ERROR_LOG_PATH=${ATM_ERROR_LOG_PATH:-logs/error.log}

############ COMPILER #############
#USE clang for dev, cc for default
ATM_CC=clang
CC=${ATM_CC:-cc}

CPU=NO
ATM_RPATH=NO

#gcc -c options, supplement to CFLAGS, 
#Note: The system CFLAG should be set in /cc/gcc in this case
ATM_CC_OPT=
#supplement to CORE_LIBS, .a -R -L can be set here 
#more infos in auto/lib/${libname}/conf
ATM_LD_OPT=
