#!/bin/sh
#Example:
#gcc -I option: 
#   CORE_INCS="$CORE_INCS $OPENSSL/.openssl/include"
#gcc file plus these dep files to make each .c file target .o: 
#   CORE_DEPS="$CORE_DEPS $OPENSSL/.openssl/include/openssl/ssl.h"
#gcc lib option. .a -R -L can be here 
#   CORE_LIBS="$CORE_LIBS $OPENSSL/.openssl/lib/libssl.a"

CORE_INCS="src/core"

CORE_DEPS="src/core/atm_core.h \
           src/core/atm_conn.h \
           src/core/atm_dict.h \
           src/core/atm_event.h \
           src/core/atm_hash.h \
           src/core/atm_list.h \
           src/core/atm_log.h \
           src/core/atm_main.h \
           src/core/atm_siphash.h \
           src/core/atm_str.h"

CORE_SRCS="src/core/atm_conn.c \
           src/core/atm_dict.c \
           src/core/atm_event.c \
           src/core/atm_hash.c \
           src/core/atm_list.c \
           src/core/atm_log.c \
           src/core/atm_main.c \
           src/core/atm_siphash.c \
           src/core/atm_str.c"

CORE_LIBS=""


#------------------------------------------------------
#TEST SRC Config
if [ $ATM_UNIT_TEST = YES ]; then
CORE_INCS="$CORE_INCS \
            src/test \
            src/test/core \
            src/test/os \
            src/test/os/unix"

CORE_DEPS="$CORE_DEPS \
            src/test/atm_unit_test.h \
            src/test/core/atm_test_dict.h \
            src/test/core/atm_test_event.h \
            src/test/core/atm_test_siphash.h \
            src/test/os/unix/atm_test_process.h"

CORE_SRCS="$CORE_SRCS \
            src/test/atm_unit_test.c \
            src/test/core/atm_test_dict.c \
            src/test/core/atm_test_event.c \
            src/test/core/atm_test_siphash.c \
            src/test/os/unix/atm_test_process.c"
fi


#------------------------------------------------------
#CONFIG OS TYPE DIFFERENCE SOURCE, 
CORE_INCS="$CORE_INCS \
            src/os \
            src/os/unix \
            src/os/unix/linux"

CORE_DEPS="$CORE_DEPS \
            src/os/unix/linux/atm_linux_config.h \
            src/os/unix/atm_alloc.h \
            src/os/unix/atm_process.h \
            src/os/unix/atm_sig.h \
            src/os/unix/atm_net.h"

CORE_SRCS="$CORE_SRCS \
            src/os/unix/atm_alloc.c \
            src/os/unix/atm_process.c \
            src/os/unix/atm_sig.c \
            src/os/unix/atm_net.c"
