#!/bin/sh
echo "Configuration summary"


if [ $USE_THREADS = YES ]; then
    echo "  + using threads"
fi

case $ATM_LIBATOMIC in
    YES)   echo "  + using system libatomic_ops library" ;;
    NO)    ;; # not used
    *)     echo "  + using libatomic_ops library: $ATM_LIBATOMIC" ;;
esac

echo


cat << END

  platform info: "$ATM_SYSTEM $ATM_RELEASE $ATM_MACHINE"

  $ATM_BINARY_NAME path prefix: "$ATM_PREFIX"
  $ATM_BINARY_NAME binary file: "$ATM_PREFIX/$ATM_BIN_PATH"
  $ATM_BINARY_NAME configuration file: "$ATM_PREFIX/$ATM_CONF_PATH"
  $ATM_BINARY_NAME pid file: "$ATM_PREFIX/$ATM_PID_PATH"
END

if test -n "$ATM_ERROR_LOG_PATH"; then
    echo "  $ATM_BINARY_NAME error log file: \"$ATM_PREFIX/$ATM_ERROR_LOG_PATH\""
else
    echo "  $ATM_BINARY_NAME logs errors to stderr"
fi
