#!/bin/sh
echo "checking for $ATM_SYSTEM specific features"

case "$ATM_PLATFORM" in
    Linux:*)
        . auto/os/linux/conf
    ;;
    Darwin:*)
        echo "Darwin not support yet......."
        exit 1
        . auto/os/darwin/conf
    ;;
    *)
        cat << END
$0: current PLATFORM [$ATM_PLATFORM] has not support yet
END
        exit 1
    ;;
esac


case "$ATM_MACHINE" in
    i386 | i686 | i86pc)
        have=ATM_HAVE_NONALIGNED . auto/have
        ATM_MACH_CACHE_LINE=32
    ;;
    amd64 | x86_64)
        have=ATM_HAVE_NONALIGNED . auto/have
        ATM_MACH_CACHE_LINE=64
    ;;
    sun4u | sun4v | sparc | sparc64)
        have=ATM_ALIGNMENT value=16 . auto/define
        # TODO
        ATM_MACH_CACHE_LINE=64
    ;;
    ia64 )
        have=ATM_ALIGNMENT value=16 . auto/define
        # TODO
        ATM_MACH_CACHE_LINE=64
    ;;
    *)
        have=ATM_ALIGNMENT value=16 . auto/define
        ATM_MACH_CACHE_LINE=32
    ;;
esac


if test -z "$ATM_CPU_CACHE_LINE"; then
    ATM_CPU_CACHE_LINE=$ATM_MACH_CACHE_LINE
fi


have=ATM_CPU_CACHE_LINE value=$ATM_CPU_CACHE_LINE . auto/define


#Check unix features
. auto/os/unix
