#!/bin/bash -

curr=$(cd `dirname $(which $0)`; pwd)

cd $curr

name="$1"
name=${name:-misc.c}
name=$(echo $name | sed 's/\.c//g')
name=$(echo $name | sed 's/\.//g')

rm Makefile

cat <<END > Makefile
CC = clang
CFLAGS = -pipe -O0 -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g 

LINK = \$(CC)

BUILD_DEPS = misc_utils.h

BUILD_INCS = -I ./ \\
	-I ../../../src/os/unix/linux \\
	-I ../../../build


END

if [ ${name} != "misc_utils" ]; then
cat <<END >> Makefile
${name}:	${name}.o \\
	misc_utils.o

	\$(LINK) -o ${name}.bin ${name}.o \\
	misc_utils.o \\
	-ldl -lpthread -Wl,-E


${name}.o:	\$(BUILD_DEPS)
	\$(CC) -c \$(CFLAGS) \$(BUILD_INCS) -o ${name}.o ${name}.c


END
fi


cat <<END >> Makefile
misc_utils.o:	\$(BUILD_DEPS)
	\$(CC) -c \$(CFLAGS) \$(BUILD_INCS) -o misc_utils.o misc_utils.c


END


cat <<END >> Makefile
.PHONY:clean
clean:
	rm -rf *.o *.bin
END

make clean

if ! [ -d "../../../build" ]; then
    (cd ../../../; ./configure)
fi

make

if [ -x ${name}.bin ]; then

cat << EOF 


---------------MISC RUN-----------------


EOF
    ./${name}.bin
cat << EOF 


---------------MISC FIN-----------------


EOF
fi
