#!/bin/sh
echo -n "checking for uintptr_t ..."

cat << END >> $ATM_AUTOCONF_ERR

----------------------------------------
checking for uintptr_t

END

found=no

cat << END > $ATM_AUTOTEST.c

#include <sys/types.h>
$ATM_INCLUDE_INTTYPES_H

int main(void) {
    uintptr_t i = 0;
    return (int) i;
}

END

atm_test="$CC $CC_TEST_FLAGS $CC_AUX_FLAGS \
          -o $ATM_AUTOTEST $ATM_AUTOTEST.c $ATM_LD_OPT"

eval "$atm_test >> $ATM_AUTOCONF_ERR 2>&1"

if [ -x $ATM_AUTOTEST ]; then
    echo " uintptr_t found"
    found=yes
else
    echo -n " uintptr_t not found"
fi

rm -rf $ATM_AUTOTEST*


if [ $found = no ]; then
    found="uint`expr 8 \* $atm_ptr_size`_t"
    echo ", $found used"

    echo "typedef $found  uintptr_t;"                   >> $ATM_AUTO_CONFIG_H
    echo "typedef $found  intptr_t;" | sed -e 's/u//g'  >> $ATM_AUTO_CONFIG_H
fi
